# -*- coding: utf-8 -*-
"""Dicount-calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-T_YOymPxDcOWAY3OST5POXNwyKI5IN

#  Discount Calculator with Membership
"""

import gradio as gr


custom_css = """

body {
    background: linear-gradient(135deg, #c3ec52, #0ba29d);
    font-family: 'Poppins', sans-serif;
    color: #333;
    text-align: center;
}
.gradio-container {
    background-color: #ffffff;
    border-radius: 20px;
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);
    padding: 30px;
    max-width: 700px;
    margin: 60px auto;
}
h1, h2 {
    color: #0a3d62;
}
button {
    background-color: #0ba29d !important;
    color: white !important;
    font-size: 18px !important;
    border-radius: 12px !important;
    padding: 12px 24px !important;
    transition: 0.3s;
}
button:hover {
    background-color: #08897f !important;
    transform: scale(1.05);
}
input, select, textarea {
    border-radius: 10px !important;
    border: 1px solid #ccc !important;
    padding: 10px !important;
    font-size: 16px !important;
}
"""

#  Original Logic – Converted for Gradio
def discount_calculator(quantity, membership):
    unit_price = 5
    result = ""

    # Outer condition – Quantity discount
    if quantity > 10:
        discount_rate = 0.10
        result += " Quantity Discount Applied: 10% off\n"
    else:
        discount_rate = 0.0
        result += " No Quantity Discount Applied\n"

    # Calculate price after quantity discount
    subtotal = quantity * unit_price
    discount_amount = subtotal * discount_rate
    price_after_discount = subtotal - discount_amount

    # Nested condition – Membership bonus
    if membership.lower() == "yes":
        result += "Premium Member Bonus: Additional $5 off\n"
        final_price = price_after_discount - 5
    elif membership.lower() == "no":
        result += " No Membership Bonus Applied\n"
        final_price = price_after_discount
    else:
        result += "Invalid input for membership. Please enter 'yes' or 'no'.\n"
        final_price = price_after_discount

    # Final output

    result += f" Subtotal: ${subtotal:.2f}\n"
    result += f" Discount Applied: ${discount_amount:.2f}\n"
    result += f" Price After Discount: ${price_after_discount:.2f}\n"
    result += f" Final Price to Pay: ${final_price:.2f}\n"


    return result


# Gradio Interface
with gr.Blocks(css=custom_css, title="Discount Calculator with Membership") as demo:
    gr.Markdown("# **Discount Calculator with Membership**")
    gr.Markdown("### Calculate your final price based on quantity and membership status")

    quantity = gr.Number(label="Enter Number of Items", value=1, precision=0)
    membership = gr.Radio(["yes", "no"], label="Are you a premium member?")

    output = gr.Textbox(label="Result", placeholder="Your calculated price will appear here...", lines=8)
    btn = gr.Button("Calculate Final Price")

    btn.click(fn=discount_calculator, inputs=[quantity, membership], outputs=output)

#Launch App
if __name__ == "__main__":
    demo.launch()